version : '3'
services:
        db:
                image: mysql:5.7
                restart: always
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: wordpress
                        MYSQL_PASSWORD: password

        wordpress:
                depends_on:
                        - db
                image: wordpress:latest
                ports:
                        - "8000:80"
                restart: always
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: password
        python:
                build: ./content
                ports:
                        - "5000:5000"
                volumes:
                        - ./content/code:/code
                image: "redis:alpine"

volumes:
        db_data:

